
import { GoogleGenAI } from "@google/genai";
import { SYSTEM_PROMPT } from "../constants";

export const generateStory = async (): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: "Tell me a new ridiculous one-sentence story.",
      config: {
        systemInstruction: SYSTEM_PROMPT,
        temperature: 1.0,
      },
    });

    return response.text?.trim() || "The story machine is currently daydreaming.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateImage = async (prompt: string, artist?: string, style?: string): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    let styleDescription = "The style should be dreamlike, artistic, and visually striking with a high degree of imagination.";
    if (style) {
      styleDescription = `The artistic style must strictly follow a '${style}' aesthetic.`;
    }
    
    const artistModifier = artist ? `This piece should be heavily influenced by the surrealist work of ${artist}.` : "";
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            text: `High-definition digital art: A whimsical and dreamlike surrealist illustration with a vibrant colors palette. The subject is the following bizarre story fragment: "${prompt}". Technical specifications: ${styleDescription} ${artistModifier} Composition: surreal, evocative, and high-contrast. Use a professional digital art medium to create a vivid, imaginative masterpiece suitable for a world-class surrealist exhibit.` 
          }
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Image Generation Error:", error);
    throw error;
  }
};
